[project]
name = "beans-zero"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "datasets>=3.3.2",
    "pycocoevalcap>=1.2",
    "pydantic>=2.10.6",
    "scikit-learn>=1.1.1",
    "xgboost>=1.6.1",
]
