# Boiler plate test suit for ESP projects

name: ESP Project CI

# Runs on pushes to master and all pull requests
on:    # yamllint disable-line rule:truthy
    push:
        branches: [main]
    pull_request:

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.10]
        steps:
            # add step to install java 8 from open-jdk
            - name: Install Java 8
              run: |
                  sudo apt-get update
                  sudo apt-get install -y openjdk-8-jre
            - uses: actions/checkout@v2
            - name: Enable caching
              uses: astral-sh/setup-uv@v5
              with:
                  enable-cache: true
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Full dependencies
              run: |
                  uv pip install --system -r requirements.txt
                  uv pip install --system -r requirements-dev.txt
            - name: Display Python version
              run: python -c "import sys; print(sys.version)"
            - name: Consistency tests with pytest
              run: |
                  pytest tests/consistency
            - name: Unittests with pytest
              run: |
                  pytest tests/unittests
            - name: Doctests with pytest
              run: |
                  pytest --doctest-modules beans_zero
            - name: Integration tests with pytest
              run: |
                  pytest tests/integration
